version: '3.8'
services:

  rowa-backend:
    image: emilsallem/rowa-backend:dev-latest
    container_name: backend
    ports:
      - 3000:3000
    #devices:
      #- "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - TZ="Europe/Berlin"
    volumes:
      -  "${pwd}/backend/src/main/rowa.db:/ROWA/rowa.db"
  
   
  rowa-frontend:
    image: emilsallem/rowa-frontend:dev-latest
    container_name: frontend
    ports:
      - 8080:80
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
      
    command: --interval 120 --debug
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - rowa-frontend
      - rowa-backend
      