scrape_configs:
- job_name: fluentd
  scrape_interval: 5s
  static_configs:
  - targets:
    - 'localhost:24231'
  metrics_path: /metrics
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8081